{
 "title": "DittoTwin",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "DT Location",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "queryText": "ModemStatus/properties/", "thingID": "org.acme:my-device-2" }
   ]
  },
  {
   "title": "LTE RSRQ (dB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/rsrq",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "MCC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/mcc",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "MNC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/mnc",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "5G SNR (dB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/snr",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "LTE PCI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/pci",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "5G PCI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/pci",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "LTE SNR (dB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/snr",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "5G RSRQ (dB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/rsrq",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "E2E Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "queryText": "MessageDelay/properties/delay", "thingID": "org.acme:my-device-2" }
   ]
  },
  {
   "title": "LTE RSRP (dBm)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/rsrp",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "5G RSRP (dBm)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/rsrp",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "RAT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/ratMode",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "vOBU Speed (km/h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Dynamics/properties/highFrequencyContainer/speed/speedValue",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "Throughput RX (b/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "queryText": "NetworkThroughput/properties/rx_bytes",
     "thingID": "org.acme:my-device-2"
    }
   ]
  },
  {
   "title": "LTE RSSI (dBm)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/rssi",
     "thingID": "org.acme:my-device-2"
    }
   ]
  }
 ]
}