{
 "title": "DittoTwins",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "ThingID", "label": "Thing ID", "query": "things" }
  ]
 },
 "panels": [
  {
   "title": "Advised Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryText": "advisedSpeed" }
   ]
  },
  {
   "title": "Trajectory Visualization",
   "type": "text",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"$VIDEO_URL\" width=\"100%\" />"
   }
  },
  {
   "title": "LTE RSRQ (dB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/rsrq"
    }
   ]
  },
  {
   "title": "MCC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/mcc"
    }
   ]
  },
  {
   "title": "MNC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/mnc"
    }
   ]
  },
  {
   "title": "5G SNR (dB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/snr"
    }
   ]
  },
  {
   "title": "LTE PCI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/pci"
    }
   ]
  },
  {
   "title": "5G PCI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/pci"
    }
   ]
  },
  {
   "title": "LTE SNR (dB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 6 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/snr"
    }
   ]
  },
  {
   "title": "5G RSRQ (dB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/rsrq"
    }
   ]
  },
  {
   "title": "E2E Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 8 },
   "targets": [
    { "queryText": "MessageDelay/properties/delay" }
   ]
  },
  {
   "title": "LTE RSRP (dBm)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 11 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/rsrp"
    }
   ]
  },
  {
   "title": "5G RSRP (dBm)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/nr/rsrp"
    }
   ]
  },
  {
   "title": "RAT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/ratMode"
    }
   ]
  },
  {
   "title": "vOBU Speed (km/h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Dynamics/properties/highFrequencyContainer/speed/speedValue"
    }
   ]
  },
  {
   "title": "Throughput RX (b/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 14 },
   "targets": [
    {
     "queryText": "NetworkThroughput/properties/rx_bytes"
    }
   ]
  },
  {
   "title": "Throughput TX (b/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 14 },
   "targets": [
    {
     "queryText": "NetworkThroughput/properties/tx_bytes"
    }
   ]
  },
  {
   "title": "LTE RSSI (dBm)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 16 },
   "targets": [
    {
     "queryText": "ModemStatus/properties/modemStatus/lte/rssi"
    }
   ]
  }
 ]
}